services:
  postgres:
    image: postgres:17-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data:cached
      - ./api/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  api:
    build:
      context: api
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - 8888:8888

#  frontend:
#    build:
#      context: frontend
#      dockerfile: Dockerfile
#    stdin_open: true
#    volumes:
#      - "./frontend:/app:cached"
#      - "./frontend/node_modules:/app/node_modules:cached"
#    environment:
#      - NODE_ENV=development
#    ports:
#      - 3000:3000

volumes:
  db-data:
