#!/usr/bin/env python3
import os, sys
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

import typer

from common.log import Log
from core.user_cli import user
from core.project_cli import project

log = Log.getChild("cli")

app = typer.Typer()
app.add_typer(user, name='user')
app.add_typer(project, name='project')

if __name__ == '__main__':
    app()


